Homework_27_done
eugene-okulik/Anatoli_Kanavalchyk pull request #28
Opened 2024-08-04 20:08 UTC by Anatoli4441

2024-08-05 08:25 UTC, eugene-okulik requested changes
Всё не могу понять почему ты пытаешься сам сочинить page. У меня pytest не может запустить эти тесты, а вот такой запускает
```python
from playwright.sync_api import sync_playwright


def test_color_change(page):
    # with sync_playwright() as p:
    #     if browser_name == 'chromium':
    #         browser = p.chromium.launch()
    #     elif browser_name == 'firefox':
    #         browser = p.firefox.launch()
    #     elif browser_name == 'webkit':
    #         browser = p.webkit.launch()
    #     else:
    #         raise ValueError(f"Unsupported browser: {browser_name}")
    #
    #     context = browser.new_context()
    #     page = context.new_page()

        page.goto('https://demoqa.com/dynamic-properties')

        color_change_button = page.locator('button#colorChange')

        page.wait_for_selector('button#colorChange.text-danger')

        color_change_button.click()

        # browser.close()


# for browser_type in ['chromium', 'firefox', 'webkit']:
#     test_color_change(browser_type)
```

2024-08-05 08:25 UTC, eugene-okulik commented on homework/Homework_27/test_task_1_playwright.py
> +        page = context.new_page()
А что ты здесь сделал того, что изменяет работу стандартной фикстуры page? Если у тебя нет каких-то дополнительных настроек, то вообще не нужно возиться ни с пейджем, ни с браузером, ни с контекстом. Просто пользуешься встроенной фикстурой.

2024-08-05 13:44 UTC, Anatoli4441 commented on homework/Homework_27/test_task_1_playwright.py
> +        page = context.new_page()
У меня без фикстур этих ничего не работало

Переустановил playwrigth и работает теперь

2024-08-06 08:54 UTC, eugene-okulik approved these changes

2024-08-06 08:54 UTC, merged